### ISSUE TITLE
Mutate Division and Multiplication

### ISSUE THREAD

**Issue by MayaGans** [gvwilson/tidyblocks#131]
The results of dividing columns of the color data frame result in NaNs ?

**Comment by gvwilson** [comment]
Can you please describe which fields you're dividing so I can try to reproduce? (This could be a string-vs-number issue.)

**Comment by MayaGans** [comment]
I'm out of ideas because the typeof row is showing that the columns are numbers.... 

<img width="319" alt="Screen Shot 2019-09-08 at 7 25 27 PM" src="https://user-images.githubusercontent.com/6053906/64497838-76a0dc80-d26e-11e9-8caa-4efdbdb0df1f.png">

255 * 255 shouldn't equal NaN 

It doesn't seem to be an issue for any other dataset though?
