### ISSUE TITLE
Arrange block (using Sort and Reverse)

### ISSUE THREAD

**Issue by MayaGans** [gvwilson/tidyblocks#140]
The dplyr block for sort is `arrange` - should I change the name of this block? I was also thinking we could add a check box for descending rather than have reverse as its own block? Thoughts?

**Comment by gvwilson** [comment]
1. I think `sort` is less ambiguous than `arrange`, but I'm neutral on the change.
2. Yes, a checkbox for "descending" would be great.

**Comment by MayaGans** [comment]
Closed with #153
