### ISSUE TITLE
Type text for column names directly instead of in a text values block?

### ISSUE THREAD

**Issue by jrosen48** [gvwilson/tidyblocks#161]
Thank you all for an amazing contribution. I can't begin to say how useful and impressive this work is. I's incredibly intuitive. 

Something I've encountered as I started to use tidyblocks is I continue to want to type text/the name of a variable directly as an argument. For example, below, instead of dragging the *text* values block into the right side of the mutate and then typing the name of the column, "red" (left), would it be possible to just type "red" as the right side of the mutate directly?

<img width="474" alt="Screen Shot 2019-09-08 at 8 19 22 AM" src="https://user-images.githubusercontent.com/4596214/64488084-6575b280-d211-11e9-9f96-aabfd82d5fe6.png">

Is this not desirable given how block-based coding does and should work - should there be the extra step of dragging the *text* values block there, first?

Looking forward to following the development and using this with teachers and students with whom I work as an education researcher.

**Comment by MayaGans** [comment]
Thank you so much for your interest and for playing with tidyblocks, I really appreciate your feedback so keep it coming! If I understand your question correctly, you're suggesting the field in the mutate block should be a direct text input (like 'new_column')? If so, this would inhibit adding nested blocks like:

<img width="323" alt="Screen Shot 2019-09-08 at 7 15 35 PM" src="https://user-images.githubusercontent.com/6053906/64497652-15c4d480-d26d-11e9-9ffa-91375a71419c.png">

We've changed a lot of the transformation blocks to have direct column inputs where we can, but if we did this anywhere with possible nesting structure we'd be limiting the block's application. 

I hope this addresses your question? If not, I'd love to discuss this further. Thank you again for your comments.
