### ISSUE TITLE
Wrong Error - data_urlCSV

### ISSUE THREAD

**Issue by MayaGans** [gvwilson/tidyblocks#164]
If you run the readCSV block without providing a url, the error is `Cannot read property 'plot' of null` and not what's in the generator code `[block ${block.tbId}] empty URL in urlCSV block`?

**Comment by MayaGans** [comment]
I see this issue as `Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///Users/mayagans/Documents/tidyblocks-1/url'.` which I think stems from

```
 readCSV (url) {
    const request = new XMLHttpRequest()
    request.open('GET', url, false)
    request.send(null)

    if (request.status !== 200) {
      console.log(`ERROR: ${request.status}`)
      return null
    }
    else {
      return csv2TidyBlocksDataFrame(request.responseText, Papa.parse)
    }
 }
```

How would we change the error to reflect the generator's and not this one? Do we even want to?

**Comment by gvwilson** [comment]
Can we put the following at the start of `readCSV`:

```
tbAssert((url !== null) && (url.length > 0),
    `Cannot fetch empty URL`)
```

That'll throw the right kind of error with a useful error message (maybe)?
