### ISSUE TITLE
concat datetime blocks

### ISSUE THREAD

**Issue by MayaGans** [gvwilson/tidyblocks#166]
1. When you grab the year/month it turns into a numeric - this should stay a date object, right? Trying to convert just a year to a date gives the wrong result. 

<img width="487" alt="Screen Shot 2019-09-09 at 8 15 18 AM" src="https://user-images.githubusercontent.com/6053906/64538528-0891ff00-d2da-11e9-996f-17fdbb83dc36.png">

2. What if I wanted to mutate a date to the year AND month? It seems a little long winded to mutate a year column, then mutate a month column, then concatenate them both, but I think that might be preferred to the and block? Will need bug 1 to work in order to concatenate year and month (not add them as numbers).

<img width="565" alt="Screen Shot 2019-09-09 at 8 08 37 AM" src="https://user-images.githubusercontent.com/6053906/64538094-3f1b4a00-d2d9-11e9-909f-48b216625b16.png">

**Comment by gvwilson** [comment]
Converting to year, month, or day gives a numeric result (1-based for months within years and days within months). To construct the string `2019-09` we will need:
1.  mutate that does extract year + convert to string and saves as a column, plus mutate that does extract month + convert to string and saves as another column, and then string concatenation (which hasn't been written yet)
2. a `date.format` block that takes a string like 'YYYY-MM` (typed in) and turns the date into that.
