### ISSUE TITLE
Linear Regression Block

### ISSUE THREAD

**Issue by MayaGans** [gvwilson/tidyblocks#193]
To answer APSTATS_2018_Q1:

* Add regression model block which prints out summary statistics
* Add regression line to scatter plot [see ISSUE #38]

**Comment by gvwilson** [comment]
Is this the same as #38 ?

**Comment by MayaGans** [comment]
I don't think so, but definitely related. I think we need a block like geom_smooth that adds a line to a plot (38), and here I'm suggesting a within statistics family of blocks, a block that you can create a linear model and get the summary output like intercept, residuals, r^2 etc etc
