### ISSUE TITLE
Remove Undefined or NA 

### ISSUE THREAD

**Issue by MayaGans** [gvwilson/tidyblocks#230]
Currently to remove undefined or NAs we need to convert a number column to string, then remove the string undefined/NA then convert back to number to do math. Can we come up with some block to remove undefined or NAs despite the column being a string? Maybe convert to text behind the scenes? 

https://github.com/tidyblocks/tidyblocks/blob/master/examples/openintrostats-advanced-highschool-statistics/ch_summarizing_data/Section%202.2/README.md#example-226

**Comment by gvwilson** [comment]
Sure - if I add a "value" block with the fixed value "undefined" so that we can (for example) filter by columns that are or are not undefined, does that work?
