### ISSUE TITLE
Replace value with another value?

### ISSUE THREAD

**Issue by MayaGans** [gvwilson/tidyblocks#231]
One of the examples asked 

> what if you replace the max `num_char` with 150 ? 

I thought this logic would work but it resulted in a true/false column, not a column of existing numbers and only replacing 64.041 with 150.

<img width="603" alt="Screen Shot 2019-10-23 at 12 45 41 PM" src="https://user-images.githubusercontent.com/6053906/67428479-0dadc380-f593-11e9-9ac5-8f4358414d30.png">

Do we have a way to change a number or would we need additional blocks? What pipeline of blocks do you suggest for changing this value?

**Comment by gvwilson** [comment]
Try: `if [num_char > 64.4] then [150] else [num_char]` - right now, the `then` and `else` branches are equality tests that produce true or false (because `=` is *not* assignment).
