### ISSUE TITLE
code generation bug with stray summarize block

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/tidyblocks#252]
1. Create a pipeline with the `colors` dataset, grouped by `red, green`, filtered by `red > 0`.
2. Run - good.
3. Add a block to summarize `blue mean`.
4. Run - good.
5. Drag the summarize block so it is disconnected from the pipeline (undocked) but do _not_ delete it.
6. Run - whoops. The summarize is still taking effect (screenshot).

![Screen Shot 2019-10-28 at 7 28 22 PM](https://user-images.githubusercontent.com/911566/67725632-6d540680-f9b9-11e9-856c-822c8d85bbec.png)

Generated code:
```
/* tidyblocks start */ TidyBlocksManager.register([], () => { environment.readCSV('https://raw.githubusercontent.com/tidyblocks/tidyblocks/master/data/colors.csv').groupBy(1, ['red','green']).filter(3, (row) => tbGt(4, row, (row) => tbGet(5, row, 'red'), (row) => (0))) .summarize(7, [undefined, tbMean, 'blue'])
```

**Comment by MayaGans** [comment]
Closed with PR #255
