### ISSUE TITLE
Create shaded diagrams to display results of t-test

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/tidyblocks#270]
Mine suggests using diagrams like these to show results of t-tests, with the numerical values in the captions.
![Screen Shot 2019-10-31 at 1 52 10 PM](https://user-images.githubusercontent.com/911566/67972803-c2746000-fbe5-11e9-84e7-24b7d3263125.png)

**Comment by gvwilson** [comment]
- https://twitter.com/brycem/status/1189968097458839552
- https://twitter.com/jakevdp/status/1189973802806956032
- https://twitter.com/koopdakoop/status/1189973037166350337

**Comment by MayaGans** [comment]
Closed with PR #286
