### ISSUE TITLE
Example R generators

### ISSUE THREAD

**Issue by gdbassett** [gvwilson/tidyblocks#298]
I'm trying to find a generator to use for an example of how to add a R function to tidyblocks, (specifically https://github.com/vz-risk/verisr/blob/master/R/getenumCI2021.R). The documentation says to look in generators/r/something.js, nowever I don't see the directory or any generators that are obviously R based.  If there's anything you can point me to I'd appreciate it! 
 Thanks for the help!

**Comment by gvwilson** [comment]
Hi Gabe,
My apologies for the fossil docs - we took out the R support while experimenting with better ways to generate JavaScript. If you're interested in chatting about where we are and where we're going, please mail me (greg.wilson@rstudio.com) and we'll find some time to get on Zoom.
Thanks,
Greg
