### ISSUE TITLE
Redirect user to correct dropdown (and tabs) given pipeline

### ISSUE THREAD

**Issue by MayaGans** [gvwilson/tidyblocks#321]
### Feature 1: Auto-navigate to selected dropdown within tab

Ideally if I do some data manipulation and use the `Report` block to create a new a dataset called `Red`, then I should automatically be taken to the `Red` dropdown. [I forget _every_ time that the pipeline actually ran and I'm just on the colors dropdown 🤦‍♀️ ]

### Feature 2: Auto-navigate to either data or plot tab given last block?

I know we have the little dot indicator but if I'm on the data tab but my pipeline ends with a plot block is there a way to automatically redirect me to that tab?

Thoughts @DarkMetroid? I have zero idea how difficult this would be to implement....

**Comment by DarkMetroid** [comment]
Feature 1 seems doable, I'll add that.

For Feature 2 I think it's doable as well, the one question would just be figuring out what tab we want to jump to in different cases. Tracing through and looking at the blocks we'd probably want to keep to the javascript and pass with the `env`. 

Would it work to just have the convention that if we have a plot, report or stats block jump to that page (in that order of precedence), if we're on a 'stale' tab (to avoid bouncing people off of what they're looking at I'm thinking).

**Comment by MayaGans** [comment]
I love that idea! What say you, @gvwilson ?

**Comment by gvwilson** [comment]
1.  Suppose I report three new datasets when the program runs - where should TidyBlocks take me?
2.  Only way to find out about the "jump to tab" feature is to try it out...

**Comment by DarkMetroid** [comment]
1. I'm thinking we just default to whatever report appears first in the env, not sure if there'd be any way of being more discerning.

**Comment by MayaGans** [comment]
The first or last of the three? I feel like that's better than staying on the old dataset since it looks like nothing happened...

**Comment by DarkMetroid** [comment]
First 'report' dataset I'm thinking (so it'll be changed from the 'userData' dataset that loads initially).
