### ISSUE TITLE
Github Actions Testing

### ISSUE THREAD

**Issue by DarkMetroid** [gvwilson/tidyblocks#323]
Thinking it makes sense to set-up `npm run tests` while fiddling with that stuff. Should we just run it on PRs @gvwilson ?

**Comment by gvwilson** [comment]
By "set up" do you mean "report status of tests for each PR"? In which case yes please and thank you.

**Comment by DarkMetroid** [comment]
Yup, should trigger on all new PRs (my current one was added before the update).
