### ISSUE TITLE
help links navigate to broken css page in firefox

### ISSUE THREAD

**Issue by jas1** [gvwilson/tidyblocks#325]
help links ( the **?** icon on the top right corner )  ;  
the 3 links work but their css is missing

navigate to broken css page in firefox, 
huge logos, and small characters, also nonformated stuff.

looks like css missing: 

https://tidyblocks.tech/dist_production/css/base.min.css

trying to access it , gives 404.

hope it helps, 
keep the awsome work :smile:   :partying_face: !

**Comment by DarkMetroid** [comment]
Thanks for flagging this, forgot to update the css path there >.<
