### ISSUE TITLE
Add k-means clustering

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/tidyblocks#374]
https://simplestatistics.org/docs/#ckmeans

**Comment by demar01** [comment]
Not sure where to find the data to translate..

**Comment by gvwilson** [comment]
My apologies - I should add to our notes.

1.  In this case, please look in `blocks/stats.js` and scroll down to the k-means clustering and silhouette blocks (starting around line 105). I've copied strings from other blocks, but I don't know if they're right.

2.  In general, if you have `node` installed, you can use `npm run check` to get a list of all untranslated strings for all blocks. I'll add an issue for myself to document how to do that.

Thanks,
Greg

**Comment by demar01** [comment]
Hi Greg,  

1. I see how to do it now. 
2.I do not have node install, that's probably why I could not see it.

Cheers
Maria

**Comment by gvwilson** [comment]
...and I hadn't documented any of this because it was clear in my head and I forgot that you can't read my mind... :-) Just filed a pull request with a few more details - hope it helps.
