### ISSUE TITLE
Drop down menu for "User Data" block not available

### ISSUE THREAD

**Issue by larnsce** [gvwilson/tidyblocks#426]
Thank for your for this brilliant work!

**(Reproducible) Example**

- The documentation for the Block __User Data__ says: "__drop down__: Select dataset by name." 
- I loaded a CSV file from my local machine and from a URL.
- Both times I can find the data on the right pane in the tab "Data" by clicking on the down arrow. The name of the object is the name of the CSV file.
- But, I don not get a drop down menu in the User Data block. I have to type the name of the object to get the data loaded in the block
- I have tried with Firefox 82.0.2 and Chrome 86.0.4240.111.

**Question/Bug?** Has the drop down been removed or is this an issue on my side? I can see it in the @MayaGans video demonstration at the rstudio::conf 2020 (great lighting talk!)

**Feauture request?** It would be great if it was able to name the data object as the CSV is imported. Some CSVs from URLs have long names that make it cumbersome to type them into the User Data block Is it possible to give a name to the  the imported dataset with a name other than by renaming the original CSV?

**Comment by gvwilson** [comment]
@DarkMetroid can you please confirm you're seeing this?

**Comment by DarkMetroid** [comment]
Yup, behavior is as mentioned. I don't think we removed anything (knowingly) during the update.

Having a dropdown makes a ton of sense, I'll take a look and put a PR up (might be sometime next week).

**Comment by DarkMetroid** [comment]
Took a look at things, it's pretty simple for us to add static dropdown lists to items, but dynamic dropdowns like we'd need for loaded CSVs get a bit difficult. Essentially we're passing all our JS block stuff to react and loading them at the start, so editing/recomputing them can't happen easily atm.

What we could do fairly easily is just let people assign a name when they're loading the CSV. I kind of like the idea of keeping the same initial window, and then after they click 'Select' or 'Load' they get prompted to confirm the name (we auto-fill with the name of the file).

<img width="384" alt="Screen Shot 2020-11-29 at 2 03 04 PM" src="https://user-images.githubusercontent.com/1018268/100551131-db1dd200-324c-11eb-8b94-4c386916995f.png">

**Comment by larnsce** [comment]
Thank you for looking at this. I think if you make it possible to name the loaded CSV then a dropdown menu is not necessary. In this case it's probably even better to explicitly type the name of the data object that we just assigned by loading it. Would be great if this option was available both for local files as well as URL uploads.
