### ISSUE TITLE
Support for unary arithmetic and logical operations

### ISSUE THREAD

**Issue by gvwilson** [gvwilson/tidyblocks#48]
We need `not` and negation.

**Comment by MayaGans** [comment]
Do you mean like this? Can be found in the `variable_compare` block <img width="273" alt="Screen Shot 2019-08-21 at 7 03 16 AM" src="https://user-images.githubusercontent.com/6053906/63434176-cca60100-c3e1-11e9-94ae-44c459850b88.png">

**Comment by gvwilson** [comment]
I was thinking something like "- Petal_Length" or "not aMountainClimber" - if the operation in the Filter block only has one column (on the right side), code generation doesn't work properly right now. I also think it's not intuitive - leaving a column name slot blank on the left isn't going to be something people think of themselves (?).
